version: "3.7"
services:
  dialog_office_spend:
    environment:
      - BOT_TOKEN=TOKEN
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./db.db
        target: /app/db.db
